services:
  app:
    build: .
    image: ghcr.io/OWNER/fastapi-actions-demo:dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    volumes:
      - .:/app
