name: CI (Dockerized)

on:
  push:
  pull_request:

jobs:
  ci-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image (with linters & pytest)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: dev
          tags: app-dev:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pytest (coverage)
        run: docker run --rm -v "$PWD:/app" -e PYTHONPATH=/app app-dev:ci pytest -q --cov=app --cov-report=xml --cov-fail-under=90

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
